[package]
name = "muz_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
regex = "1.10.5"
rand = "0.8.5"
indexmap = "2.2.6"

[profile.dev]
opt-level = 3

[profile.release]
overflow-checks = true